name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.21.0

      - name: Run tests
        run: go test ./...
